dist: xenial

language: php

services:
  - mysql
  - docker

addons:
  apt:
    packages:
      - libxml2-utils

before_install:
  - nvm install
  - nvm use

install:
  - npm install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - export DIFF_HEAD=HEAD
  - source "$DEV_LIB_PATH/travis.install.sh"

before_script:
  - phpenv config-rm xdebug.ini || echo "xdebug.ini does not exist."

script:
  - source "$DEV_LIB_PATH/travis.script.sh"

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

jobs:

  include:

    - stage: lint
    - php: "5.6"
      script:
        - npm run lint
        - npm run build

    - php: "7.4"
      script:
        - npm run lint
        - npm run build

    - stage: test
    - name: PHP unit tests (7.4, WordPress trunk)
      php: "7.4"
      env: WP_VERSION=trunk DEV_LIB_ONLY=phpunit
      script:
        - npm run env:start
        - npm run wp -- wp core install --title=WordPress --admin_user=admin --admin_password=password --admin_email=admin@example.com --skip-email --url=http://localhost:8088 --quiet
        - npm run wp -- wp plugin activate cloudinary
        - npm run test

notifications:
  email: false

cache:
  npm: true
  directories:
    - "$HOME/.composer/cache"
